/** Demonstration articles used by the seed script. Replace them from the admin panel. */
const html = {
  p: (text) => `<p>${text}</p>`,
  h2: (text) => `<h2>${text}</h2>`,
  h3: (text) => `<h3>${text}</h3>`,
  ul: (items) => `<ul>${items.map((item) => `<li>${item}</li>`).join('')}</ul>`,
  ol: (items) => `<ol>${items.map((item) => `<li>${item}</li>`).join('')}</ol>`,
  quote: (text) => `<blockquote>${text}</blockquote>`,
};

const articles = [
  {
    title: 'Getting Started with the MERN Stack',
    category: 'engineering',
    tags: ['react', 'node', 'mongodb'],
    excerpt: 'A practical map of how MongoDB, Express, React and Node.js fit together, and where beginners usually get stuck.',
    hue: 245,
    alt: 'Abstract indigo gradient with layered geometric shapes',
    body: [
      html.p('The MERN stack is popular because a single language, JavaScript, runs everywhere: in the database shell, on the server and in the browser. That shared vocabulary makes it easier for a small team to move quickly.'),
      html.h2('How the pieces fit'),
      html.ul(['<strong>MongoDB</strong> stores documents that look like the JSON your API returns.', '<strong>Express</strong> maps URLs to handlers and keeps middleware small and composable.', '<strong>React</strong> renders the interface and talks to the API over HTTP.', '<strong>Node.js</strong> runs the server and the tooling around it.']),
      html.h3('Start with the data'),
      html.p('Sketch your documents before writing any routes. Decide what belongs together, what needs its own collection, and which fields you will filter on. Those answers drive your indexes later.'),
      html.quote('Model the questions your application asks, not the objects your application has.'),
      html.p('Once the shape of the data is settled, the API and the interface tend to fall into place quickly.'),
    ],
  },
  {
    title: 'Designing Accessible Interfaces',
    category: 'design',
    tags: ['a11y', 'ux'],
    excerpt: 'Accessibility is not a final polish step. These habits make interfaces usable for everyone from the first sprint.',
    hue: 175,
    alt: 'Abstract teal gradient with soft circular shapes',
    body: [
      html.p('Accessible design starts with semantics. A real button is focusable, announced correctly and works with the keyboard without any extra code. A styled div needs all of that rebuilt by hand.'),
      html.h2('A short checklist'),
      html.ol(['Use headings in order so screen-reader users can scan the page.', 'Make sure every interactive element has a visible focus style.', 'Never rely on colour alone to communicate state.', 'Provide text alternatives for meaningful images.']),
      html.p('Test with the keyboard first. If you can complete every task without a mouse, you have already found most of the problems that affect assistive technology users.'),
      html.quote('Accessibility is what happens when you design for the widest range of human situations.'),
    ],
  },
  {
    title: 'Securing Your Express API',
    category: 'security',
    tags: ['node', 'jwt', 'owasp'],
    excerpt: 'Headers, rate limits, validation and sane error handling: the baseline every Express API should ship with.',
    hue: 12,
    alt: 'Abstract coral and violet gradient with angular shapes',
    body: [
      html.p('Most API incidents come from missing basics rather than exotic attacks. A short, boring checklist prevents the majority of them.'),
      html.h2('The baseline'),
      html.ul(['Send security headers with Helmet.', 'Validate every request body, query and parameter on the server.', 'Rate-limit authentication and any endpoint that writes data.', 'Return generic errors to clients and keep details in your logs.']),
      html.h3('Never trust the client'),
      html.p('Hiding an admin button in the interface protects nothing. Every protected route must check identity and permission on the server, every time.'),
      html.quote('Security is a property of the whole system, not a feature you add at the end.'),
    ],
  },
  {
    title: 'Writing Content That Ranks',
    category: 'seo',
    tags: ['content', 'ux'],
    excerpt: 'Search engines reward pages that answer a question clearly. Here is a repeatable way to structure an article.',
    hue: 40,
    alt: 'Abstract amber gradient with flowing lines',
    body: [
      html.p('Good SEO writing begins with a single question. If you can state what the reader wants to know in one sentence, the outline almost writes itself.'),
      html.h2('Structure that helps readers and crawlers'),
      html.ol(['Answer the question in the first paragraph.', 'Use descriptive headings that match how people search.', 'Link to related articles so readers can keep going.', 'Write a specific title and a meta description that earns the click.']),
      html.p('Resist the urge to stuff keywords. Clear language, useful examples and a fast page outperform tricks over any reasonable time frame.'),
    ],
  },
  {
    title: 'Dark Mode Done Right',
    category: 'design',
    tags: ['css', 'ux', 'a11y'],
    excerpt: 'Inverting colours is not a dark theme. Design the palette on purpose, with contrast and elevation in mind.',
    hue: 268,
    alt: 'Abstract dark violet gradient with subtle glow',
    body: [
      html.p('A good dark theme is designed, not generated. Pure black backgrounds with pure white text cause halation for many readers, so most polished products use deep greys and slightly softened text.'),
      html.h2('Principles worth following'),
      html.ul(['Express elevation with lighter surfaces instead of heavy shadows.', 'Desaturate brand colours slightly so they do not vibrate on dark backgrounds.', 'Check contrast ratios for both themes separately.', 'Respect the operating system preference, then remember the choice.']),
      html.p('Define your colours as design tokens once, then swap the whole set with a single attribute. The interface stays consistent and the code stays small.'),
    ],
  },
  {
    title: 'Understanding Refresh Token Rotation',
    category: 'security',
    tags: ['jwt', 'node', 'auth'],
    excerpt: 'Short-lived access tokens and rotating refresh tokens limit the damage of a leaked credential.',
    hue: 200,
    alt: 'Abstract blue gradient with interlocking rings',
    body: [
      html.p('An access token proves who you are for a few minutes. A refresh token lets the client obtain a new access token without asking for the password again, and it lives much longer, so it deserves more care.'),
      html.h2('Why rotate'),
      html.p('When every refresh issues a brand-new refresh token and invalidates the previous one, a stolen token becomes useless the moment the real user refreshes. Store only a hash of the current token on the server, and send it to the browser in an HTTP-only cookie so scripts can never read it.'),
      html.quote('Assume a token will leak eventually and design so that it does not matter for long.'),
    ],
  },
  {
    title: 'MongoDB Indexing Basics',
    category: 'engineering',
    tags: ['mongodb', 'performance'],
    excerpt: 'Indexes turn slow collection scans into fast lookups. Learn which ones to create and how to check they are used.',
    hue: 145,
    alt: 'Abstract green gradient with grid-like shapes',
    body: [
      html.p('Without an index, MongoDB reads every document to answer a query. That is fine for a hundred posts and painful for a million.'),
      html.h2('Rules of thumb'),
      html.ul(['Index the fields you filter and sort on together.', 'Put equality fields before range and sort fields in compound indexes.', 'Use <strong>explain()</strong> to confirm a query uses the index you expect.', 'Remove indexes nobody uses; each one slows down writes.']),
      html.p('Measure before and after. An index that does not change the query plan is only costing you storage.'),
    ],
  },
  {
    title: 'Core Web Vitals in Plain English',
    category: 'seo',
    tags: ['performance', 'ux'],
    excerpt: 'Three metrics describe how fast a page loads, responds and stays stable. Here is what they mean and how to improve them.',
    hue: 320,
    alt: 'Abstract magenta gradient with curved shapes',
    body: [
      html.p('Core Web Vitals measure real user experience: how quickly the main content appears, how soon the page reacts to input, and whether the layout jumps around while loading.'),
      html.h2('Quick wins'),
      html.ol(['Serve appropriately sized images in a modern format such as WebP.', 'Reserve space for images so the layout does not shift.', 'Split your JavaScript so each page loads only what it needs.']),
      html.p('Improving these numbers helps search visibility, but more importantly it makes the site feel better to use.'),
    ],
  },
  {
    title: 'Shipping Small: Releasing Every Week',
    category: 'product',
    tags: ['process', 'ux'],
    excerpt: 'Small, frequent releases reduce risk and speed up feedback. A look at the habits that make weekly shipping realistic.',
    hue: 95,
    alt: 'Abstract lime gradient with stacked rectangles',
    body: [
      html.p('Teams that release weekly rarely have dramatic release days. Each change is small enough to understand, test and roll back.'),
      html.h2('Habits that help'),
      html.ul(['Keep pull requests focused on one idea.', 'Hide unfinished work behind flags instead of long-lived branches.', 'Automate the checks so confidence does not depend on heroics.']),
      html.quote('If a release feels scary, release more often until it does not.'),
    ],
  },
];

const draftArticle = {
  title: 'Draft: Editorial Roadmap for Next Quarter',
  category: 'product',
  tags: ['process'],
  excerpt: 'Work in progress: themes and publishing cadence for the coming quarter.',
  hue: 220,
  alt: 'Abstract slate gradient',
  body: [html.p('This draft is visible only in the admin panel. Publish it to see it appear on the public site.')],
};

module.exports = { articles, draftArticle, html };
